export const jobListings = [
  {
      id: 1,
      job_code: 'JD1234',
      job_name: 'Senior Software Engineer',
      location: ['Doha', 'Dubai'],
      total_applications: 120,
      shortlisted_applications: 30,
      interviewed_applications: 10,
      offered_applications: 5,
      hired_applications: 3,
      dropped_applications: 2,
      published_date: '2024-11-01T09:00:00',
      status: 'published'
  },
  {
      id: 2,
      job_code: 'JD5678',
      job_name: 'Project Manager',
      location: ['Abu Dhabi', 'Manama'],
      total_applications: 80,
      shortlisted_applications: 25,
      interviewed_applications: 15,
      offered_applications: 7,
      hired_applications: 4,
      dropped_applications: 3,
      published_date: '2024-11-02T10:30:00',
      status: 'paused'
  },
  {
      id: 3,
      job_code: 'JD9101',
      job_name: 'Marketing Manager',
      location: ['Muscat', 'Dubai'],
      total_applications: 50,
      shortlisted_applications: 10,
      interviewed_applications: 5,
      offered_applications: 2,
      hired_applications: 1,
      dropped_applications: 3,
      published_date: '2024-11-03T12:00:00',
      status: 'published'
  },
  {
      id: 4,
      job_code: 'JD1121',
      job_name: 'UX Designer',
      location: ['Doha'],
      total_applications: 0,
      shortlisted_applications: 0,
      interviewed_applications: 0,
      offered_applications: 0,
      hired_applications: 0,
      dropped_applications: 0,
      published_date: '2024-11-04T14:00:00',
      status: 'pending'
  },
  {
      id: 5,
      job_code: 'JD3345',
      job_name: 'Backend Developer',
      location: ['Dubai', 'Abu Dhabi'],
      total_applications: 200,
      shortlisted_applications: 100,
      interviewed_applications: 50,
      offered_applications: 20,
      hired_applications: 15,
      dropped_applications: 10,
      published_date: '2024-11-05T16:00:00',
      status: 'published'
  },
  {
      id: 6,
      job_code: 'JD6578',
      job_name: 'Frontend Developer',
      location: ['Muscat'],
      total_applications: 30,
      shortlisted_applications: 10,
      interviewed_applications: 3,
      offered_applications: 1,
      hired_applications: 1,
      dropped_applications: 2,
      published_date: '2024-11-06T17:00:00',
      status: 'paused'
  },
  {
      id: 7,
      job_code: 'JD7890',
      job_name: 'DevOps Engineer',
      location: ['Abu Dhabi', 'Manama'],
      total_applications: 100,
      shortlisted_applications: 40,
      interviewed_applications: 20,
      offered_applications: 10,
      hired_applications: 5,
      dropped_applications: 5,
      published_date: '2024-11-07T08:00:00',
      status: 'published'
  },
  {
      id: 8,
      job_code: 'JD2345',
      job_name: 'Data Scientist',
      location: ['Doha'],
      total_applications: 0,
      shortlisted_applications: 0,
      interviewed_applications: 0,
      offered_applications: 0,
      hired_applications: 0,
      dropped_applications: 0,
      published_date: '2024-11-08T09:00:00',
      status: 'pending'
  },
  {
      id: 9,
      job_code: 'JD5679',
      job_name: 'Business Analyst',
      location: ['Dubai', 'Abu Dhabi'],
      total_applications: 150,
      shortlisted_applications: 75,
      interviewed_applications: 30,
      offered_applications: 15,
      hired_applications: 10,
      dropped_applications: 5,
      published_date: '2024-11-09T11:00:00',
      status: 'closed'
  },
  {
      id: 10,
      job_code: 'JD8765',
      job_name: 'Product Manager',
      location: ['Manama'],
      total_applications: 95,
      shortlisted_applications: 35,
      interviewed_applications: 20,
      offered_applications: 8,
      hired_applications: 4,
      dropped_applications: 3,
      published_date: '2024-11-10T13:00:00',
      status: 'published'
  },
  {
      id: 11,
      job_code: 'JD1235',
      job_name: 'Cloud Engineer',
      location: ['Doha', 'Dubai'],
      total_applications: 110,
      shortlisted_applications: 40,
      interviewed_applications: 20,
      offered_applications: 10,
      hired_applications: 5,
      dropped_applications: 5,
      published_date: '2024-11-11T15:00:00',
      status: 'paused'
  },
  {
      id: 12,
      job_code: 'JD6543',
      job_name: 'HR Manager',
      location: ['Muscat', 'Manama'],
      total_applications: 60,
      shortlisted_applications: 18,
      interviewed_applications: 8,
      offered_applications: 3,
      hired_applications: 2,
      dropped_applications: 2,
      published_date: '2024-11-12T17:30:00',
      status: 'published'
  },
  {
      id: 13,
      job_code: 'JD4321',
      job_name: 'Software Architect',
      location: ['Abu Dhabi'],
      total_applications: 0,
      shortlisted_applications: 0,
      interviewed_applications: 0,
      offered_applications: 0,
      hired_applications: 0,
      dropped_applications: 0,
      published_date: '2024-11-13T18:00:00',
      status: 'pending'
  },
  {
      id: 14,
      job_code: 'JD2143',
      job_name: 'Network Engineer',
      location: ['Dubai'],
      total_applications: 75,
      shortlisted_applications: 30,
      interviewed_applications: 12,
      offered_applications: 6,
      hired_applications: 4,
      dropped_applications: 2,
      published_date: '2024-11-14T10:00:00',
      status: 'paused'
  },
  {
      id: 15,
      job_code: 'JD9876',
      job_name: 'Full Stack Developer',
      location: ['Manama'],
      total_applications: 120,
      shortlisted_applications: 50,
      interviewed_applications: 20,
      offered_applications: 10,
      hired_applications: 6,
      dropped_applications: 3,
      published_date: '2024-11-15T11:30:00',
      status: 'closed'
  },
  {
      id: 16,
      job_code: 'JD5432',
      job_name: 'IT Support Specialist',
      location: ['Muscat'],
      total_applications: 0,
      shortlisted_applications: 0,
      interviewed_applications: 0,
      offered_applications: 0,
      hired_applications: 0,
      dropped_applications: 0,
      published_date: '2024-11-16T13:00:00',
      status: 'pending'
  },
  {
      id: 17,
      job_code: 'JD1098',
      job_name: 'System Administrator',
      location: ['Abu Dhabi', 'Doha'],
      total_applications: 150,
      shortlisted_applications: 60,
      interviewed_applications: 25,
      offered_applications: 12,
      hired_applications: 8,
      dropped_applications: 5,
      published_date: '2024-11-17T14:30:00',
      status: 'published'
  },
  {
      id: 18,
      job_code: 'JD2211',
      job_name: 'Cybersecurity Expert',
      location: ['Dubai', 'Muscat'],
      total_applications: 90,
      shortlisted_applications: 35,
      interviewed_applications: 15,
      offered_applications: 7,
      hired_applications: 5,
      dropped_applications: 3,
      published_date: '2024-11-18T16:00:00',
      status: 'paused'
  },
  {
      id: 19,
      job_code: 'JD3346',
      job_name: 'Sales Executive',
      location: ['Doha'],
      total_applications: 55,
      shortlisted_applications: 15,
      interviewed_applications: 8,
      offered_applications: 4,
      hired_applications: 2,
      dropped_applications: 1,
      published_date: '2024-11-19T17:00:00',
      status: 'published'
  },
  {
      id: 20,
      job_code: 'JD4567',
      job_name: 'Tech Support Analyst',
      location: ['Abu Dhabi'],
      total_applications: 0,
      shortlisted_applications: 0,
      interviewed_applications: 0,
      offered_applications: 0,
      hired_applications: 0,
      dropped_applications: 0,
      published_date: '2024-11-20T18:00:00',
      status: 'pending'
  }
];